language: node_js
node_js:
- lts/*
sudo: false
notifications:
  email: false
before_install:
- wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O ~/miniconda.sh;
- bash ~/miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- pip install --pre jupyterlab
install:
- npm install
- npm run build
deploy:
  provider: npm
  email: werner.greg@gmail.com
  api_key:
    secure: eIfe8BGlB+6TcD7sflBwg9AOSz4USf8OlpTxrYGd/dGD6owWw/UcRa+1UK+7SKlB9B3uSVE6ScNAjkF/SolO0hysKDryLISI7bQTIWPVIXIv0wbLRn9Z0ekxhmbOodHOReNDxDmyQl73WTmoeGe4ZJwPgzBj1NOtFNAER41Mt/D+DIrm7XShTgwDXag81XySFZZ6nYtQI4YJqAcMeC4qVwwZra92Xf1KQ9k6pm872AnCdvmcK2WVv13GRAajBoOIwBAAPYLbc8PKrofMbKMYGsrXOMfBb9Mz7IsyqMvcCYqNpfd+wtr3p0mp/JL3FseXYaL1BFwoijCAGuh4sP7YRQR9VkEEmQtUBadXJEbV2BAzhKHqrjUPYKwv2ziZWWhPKtsWbaKOZ6n5GDLySKqbhpEpRrz/Ah5+09k1vS5AZC/Kdx11+E2QG3QMzfjF9x6y9CTpUk3+4QCzt7h1ND4Xgw38+BnDkw539ewfQ0FqwBRkZjdEbdhNHDZnRLcK3PNnRjYcheduDK9FZ8OpXme25z4c/f8Il6ezof/rtZS3no1HLb/QSfPm6vPTnW/tcBPv7mpBswdBFdzGyp9FaE60eeTiMlWXgrT01YGxOzIVBDOWHALjh1DysDTTmWrYASUgL2VU5rhgfsUmbAJiPkPZQPcJ+BnclqYQczCSUDneFUU=
  on:
    tags: true
    repo: IllumiDesk/jupyter-lti
